# Generated by Django 3.2.21 on 2023-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
