# Generated by Django 3.2.21 on 2023-11-06 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20231103_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='Subscriber name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
