# Generated by Django 3.2.21 on 2023-10-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_confirmed',
        ),
    ]
