# Generated by Django 3.2.21 on 2023-09-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='safty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.safety'),
        ),
    ]
