# Generated by Django 3.2.21 on 2023-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_safty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Size'),
        ),
    ]
