# Generated by Django 3.2.21 on 2023-10-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20231031_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='watering',
        ),
        migrations.DeleteModel(
            name='Watering',
        ),
    ]
