# Generated by Django 3.2.21 on 2023-11-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20231031_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
